### PR TITLE
Provide time attributes like year, mon, day, etc

### PR DESCRIPTION
**Pull request by taldcroft**
Inspired by #18.

### CODE REVIEW

**Comment by taldcroft** [comment]
@jeanconn - please have a try.

**Comment by jeanconn** [comment]
This works for me.  I think in terms of `doy` more than `yday` but `yday` is certainly fine.

I think this also provides all that is needed for a time tuple if one wants to use time.strftime to build a time string.

I think we need to merge #17 to test this enhancement against the leap sec too, but it seems like it should all be consistent.

**Comment by taldcroft** [comment]
Astropy 1.0.3 is installed and fixes the 2015 leap second issue. I can't decide if we should merge 17 on principle. I guess I would lean slightly that way. There will be a version conflict that needs fixing.

**Comment by taldcroft** [comment]
As expected, this now needs rebase.

**Pull request merged**
